from tkinter import *

def doWhatever():
    print("buko juice")
root = Tk()

menu= Menu(root)
root.config(menu = menu)

subMenu = Menu(menu)
menu.add_cascade(label="File", menu = subMenu)
subMenu.add_command(label="New Text File", command=doWhatever)
subMenu.add_command(label="New File...", command=doWhatever)
subMenu.add_command(label="New Window", command=doWhatever)
subMenu.add_separator()
subMenu.add_command(label="Open File...", command=doWhatever)
subMenu.add_command(label="Open Folder...", command=doWhatever)
subMenu.add_command(label="Open Workspace from File...", command=doWhatever)
subMenu.add_command(label="Open Recent", command=doWhatever)
subMenu.add_separator()
subMenu.add_command(label="Add Workspace to Folder...", command=doWhatever)
subMenu.add_command(label="Save Workspace As...", command=doWhatever)
subMenu.add_command(label="Duplicate Workspace", command=doWhatever)
subMenu.add_separator()
subMenu.add_command(label="Save", command=doWhatever)
subMenu.add_command(label="Save As...", command=doWhatever)
subMenu.add_command(label="Save All", command=doWhatever)
subMenu.add_separator()
subMenu.add_command(label="Share", command=doWhatever)
subMenu.add_separator()
subMenu.add_command(label="Auto Save", command=doWhatever)
subMenu.add_command(label="Preferences", command=doWhatever)
subMenu.add_separator()
subMenu.add_command(label="Revert File", command=doWhatever)
subMenu.add_command(label="Close Editor", command=doWhatever)
subMenu.add_command(label="Close folder", command=doWhatever)
subMenu.add_command(label="Close Window", command=doWhatever)
subMenu.add_separator()
subMenu.add_command(label="Exit", command=doWhatever)

editMenu = Menu(menu)
menu.add_cascade(label="Edit",menu=editMenu)
editMenu.add_cascade(label="Undo",command=doWhatever)
editMenu.add_cascade(label="Redo",command=doWhatever)
editMenu.add_separator()
editMenu.add_cascade(label="Cut",command=doWhatever)
editMenu.add_cascade(label="Copy",command=doWhatever)
editMenu.add_cascade(label="Paste",command=doWhatever)
editMenu.add_separator()
editMenu.add_cascade(label="Find",command=doWhatever)
editMenu.add_cascade(label="Replace",command=doWhatever)
editMenu.add_separator()
editMenu.add_cascade(label="Find in Files",command=doWhatever)
editMenu.add_cascade(label="Replace in Files",command=doWhatever)
editMenu.add_separator()
editMenu.add_cascade(label="Toggle Line Comment",command=doWhatever)
editMenu.add_cascade(label="Emmet:Expand Abreviation",command=doWhatever)

selectionMenu = Menu(menu)
menu.add_cascade(label="Selection",menu=selectionMenu)
selectionMenu.add_cascade(label="Select All",command=doWhatever)
selectionMenu.add_cascade(label="Expand Selection",command=doWhatever)
selectionMenu.add_cascade(label="Shrink Selection",command=doWhatever)
selectionMenu.add_separator()
selectionMenu.add_cascade(label="Copy Line Up",command=doWhatever)
selectionMenu.add_cascade(label="Copy Line Down",command=doWhatever)
selectionMenu.add_cascade(label="Move Line Up",command=doWhatever)
selectionMenu.add_cascade(label="Move Line Down",command=doWhatever)
selectionMenu.add_cascade(label="Duplicate Selection",command=doWhatever)
selectionMenu.add_separator()
selectionMenu.add_cascade(label="Add Cursor Above",command=doWhatever)
selectionMenu.add_cascade(label="Add Cursor Below",command=doWhatever)
selectionMenu.add_cascade(label="Add Cursor to Line Ends",command=doWhatever)
selectionMenu.add_cascade(label="Add Next Occurenence",command=doWhatever)
selectionMenu.add_cascade(label="Add Previous Occurence",command=doWhatever)
selectionMenu.add_cascade(label="Select All Occurence",command=doWhatever)
selectionMenu.add_separator()
selectionMenu.add_cascade(label="Switch to Ctrl+ Click to Multi-Cursor",command=doWhatever)
selectionMenu.add_cascade(label="Column Selection Mode",command=doWhatever)

viewMenu = Menu(menu)
menu.add_cascade(label="View",menu=viewMenu)
viewMenu.add_cascade(label="Command Pallete...",command=doWhatever)
viewMenu.add_cascade(label="Open View...",command=doWhatever)
viewMenu.add_separator()
viewMenu.add_cascade(label="Appearance",command=doWhatever)
viewMenu.add_cascade(label="Editor Layout",command=doWhatever)
viewMenu.add_separator()
viewMenu.add_cascade(label="Explorer",command=doWhatever)
viewMenu.add_cascade(label="Search",command=doWhatever)
viewMenu.add_cascade(label="Source Control",command=doWhatever)
viewMenu.add_cascade(label="Run",command=doWhatever)
viewMenu.add_cascade(label="Extension",command=doWhatever)
viewMenu.add_cascade(label="Testing",command=doWhatever)
viewMenu.add_separator()
viewMenu.add_cascade(label="Problems",command=doWhatever)
viewMenu.add_cascade(label="Output",command=doWhatever)
viewMenu.add_cascade(label="Debug Console",command=doWhatever)
viewMenu.add_cascade(label="Terminal",command=doWhatever)
viewMenu.add_separator()
viewMenu.add_cascade(label="Word Wrap",command=doWhatever)
viewMenu.add_cascade(label="Sticky Scroll",command=doWhatever)

goMenu = Menu(menu)
menu.add_cascade(label="Go", menu=goMenu)
goMenu.add_cascade(label="Back",command=doWhatever)
goMenu.add_cascade(label="Forward",command=doWhatever)
goMenu.add_cascade(label="Last Edit Location",command=doWhatever)
goMenu.add_separator()
goMenu.add_cascade(label="Switch Editor",command=doWhatever)
goMenu.add_cascade(label="Switch Group",command=doWhatever)
goMenu.add_separator()
goMenu.add_cascade(label="Go to File...",command=doWhatever)
goMenu.add_cascade(label="Go to Symbol in Workspace...",command=doWhatever)
goMenu.add_separator()
goMenu.add_cascade(label="Go to Symbol in Editor...",command=doWhatever)
goMenu.add_cascade(label="Go to Definition",command=doWhatever)
goMenu.add_cascade(label="Go to Declaration",command=doWhatever)
goMenu.add_cascade(label="Go to Type Definition",command=doWhatever)
goMenu.add_cascade(label="Go to Implimintations",command=doWhatever)
goMenu.add_cascade(label="Go to References",command=doWhatever)
goMenu.add_separator()
goMenu.add_cascade(label="Go to Line/Column",command=doWhatever)
goMenu.add_cascade(label="Go to Bracket",command=doWhatever)
goMenu.add_separator()
goMenu.add_cascade(label="Next Problem",command=doWhatever)
goMenu.add_cascade(label="Previous Problem",command=doWhatever)
goMenu.add_separator()
goMenu.add_cascade(label="Next Change",command=doWhatever)
goMenu.add_cascade(label="Previous Change",command=doWhatever)

runMenu = Menu(menu)
menu.add_cascade(label="Run", menu=runMenu)
runMenu.add_cascade(label="Star Debugging", command=doWhatever)
runMenu.add_cascade(label="Run Without Debugging", command=doWhatever)
runMenu.add_cascade(label="Stop Debugging", command=doWhatever)
runMenu.add_cascade(label="Restart Debugging", command=doWhatever)
runMenu.add_separator()
runMenu.add_cascade(label="Open Configuration", command=doWhatever)
runMenu.add_cascade(label="Add Configuration", command=doWhatever)
runMenu.add_separator()
runMenu.add_cascade(label="Step Over", command=doWhatever)
runMenu.add_cascade(label="Step into", command=doWhatever)
runMenu.add_cascade(label="Step Out", command=doWhatever)
runMenu.add_cascade(label="Continue", command=doWhatever)
runMenu.add_separator()
runMenu.add_cascade(label="Toggle Breakpoint", command=doWhatever)
runMenu.add_cascade(label="New Breakpoint", command=doWhatever)
runMenu.add_separator()
runMenu.add_cascade(label="Enable all Breakpoint", command=doWhatever)
runMenu.add_cascade(label="Disable all Breakpoint", command=doWhatever)
runMenu.add_cascade(label="Remove all Breakpoint", command=doWhatever)
runMenu.add_separator()
runMenu.add_cascade(label="Install Additional Debuggers...", command=doWhatever)

terminalMenu = Menu(menu)
menu.add_cascade(label="Terminal", menu=terminalMenu)
terminalMenu.add_cascade(label="New Terminal",command=doWhatever)
terminalMenu.add_cascade(label="Split Terminal",command=doWhatever)
terminalMenu.add_separator()
terminalMenu.add_cascade(label="Run Task",command=doWhatever)
terminalMenu.add_cascade(label="Run Build Task...",command=doWhatever)
terminalMenu.add_cascade(label="Run Active File",command=doWhatever)
terminalMenu.add_cascade(label="Run Selected Text",command=doWhatever)
runMenu.add_separator()
terminalMenu.add_cascade(label="Show Running Task...",command=doWhatever)
terminalMenu.add_cascade(label="Restart Running Task...",command=doWhatever)
terminalMenu.add_cascade(label="Terminate Task...",command=doWhatever)
runMenu.add_separator()
terminalMenu.add_cascade(label="Configure Task...",command=doWhatever)
terminalMenu.add_cascade(label="Configure Build Task...",command=doWhatever)


helpMenu = Menu(menu)
menu.add_cascade(label="Help",menu=helpMenu)
helpMenu.add_cascade(label="Welcome",command=doWhatever)
helpMenu.add_cascade(label="Show All Commands ",command=doWhatever)
helpMenu.add_cascade(label="Documentation",command=doWhatever)
helpMenu.add_cascade(label="Editor Playground",command=doWhatever)
helpMenu.add_cascade(label="Show Release Notes",command=doWhatever)
helpMenu.add_separator()
helpMenu.add_cascade(label="Keyboard Shortcuts Reference",command=doWhatever)
helpMenu.add_cascade(label="Video Tutorials",command=doWhatever)
helpMenu.add_cascade(label="Tips And Tricks",command=doWhatever)
helpMenu.add_separator()
helpMenu.add_cascade(label="Join Us On Twitter",command=doWhatever)
helpMenu.add_cascade(label="Search Feature Requests",command=doWhatever)
helpMenu.add_cascade(label="Report Issue",command=doWhatever)
helpMenu.add_separator()
helpMenu.add_cascade(label="View License",command=doWhatever)
helpMenu.add_cascade(label="Privacy Statement",command=doWhatever)
helpMenu.add_separator()
helpMenu.add_cascade(label="Toggle Developer Tools",command=doWhatever)
helpMenu.add_separator()
helpMenu.add_cascade(label="Check for Updates...",command=doWhatever)
helpMenu.add_separator()
helpMenu.add_cascade(label="About",command=doWhatever)

myButton = Button(Label, text="search",command=self.button)

root.mainloop()
